### PR TITLE
change error messages of the tests to be more explicit

### PR DESCRIPTION
**Pull request by titoOdUA**
Made error messages a little more explicit and expressive

Aimed to address issue https://github.com/jetbrains-academy/rustlings-course/issues/241

### CODE REVIEW

**Comment by titoOdUA** [comment]
@bravit I don't seem to have rights to assign a reviewer but I hope this will do the trick =)

**Review by bravit — APPROVED** [review]
LGTM, thank you very much!

@sofiiako, I think this PR could be merged.

**Comment by titoOdUA** [comment]
@bravit oops, found a little bug with rendering error text in intellij via "Check" button
was running in terminal all the time, will fix it

sorry

**Comment by titoOdUA** [comment]
@bravit fixed the formatting so the text can be correctly rendered in the idea and the plugin.
Slightly modified actual test (replace backticks with single quotes due to the bug explained below).

As I understand the bug is unrelated to this repo, but just for the context I will leave notes below.

- Idea parses and renders expected and actual result automatically when assert_eq! is used
	- it gets the first param as actual and second param as expected (but renders it in different order which feels a little weird)
- there appears to be a **bug with backtick**. If text, that contains a backtick should be rendered in expected field
	- if value that would be rendered in expected field (so first argument of the assert_eq!) contains backtick ` -> it breaks output
	- if backtick is in another argument (that need to be placed and rendered in actual field) -> it rendered correctly.

**Review by bravit — APPROVED** [review]
Thank you! I never used this plugin feature to render the `assert_eq!` parameters as expected/actual. It looks great!

**Pull request merged**
